// <auto-generated />
namespace JD.Portal.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Criação_de_Projeto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criação_de_Projeto));
        
        string IMigrationMetadata.Id
        {
            get { return "201903180032244_Criação_de_Projeto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
