// <auto-generated />
namespace JD.Portal.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Criação_Responsaveis_Atendimentos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criação_Responsaveis_Atendimentos));
        
        string IMigrationMetadata.Id
        {
            get { return "201904071535484_Criação_Responsaveis_Atendimentos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
