// <auto-generated />
namespace JD.Portal.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adicionar_Diacono_No_AppUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionar_Diacono_No_AppUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070434281_Adicionar_Diacono_No_AppUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
